### ISSUE TITLE
ElasticClient.transport not available with 5.3.2

### ISSUE THREAD

**Issue by prashanttct07** [sksamuel/elastic4s#900] opened 2017-05-04 06:02 UTC
Hi All,

Not sure if this is issue but I started trying put the elastic4s with scala and getting an issue while creating connection. Below are the details which i am doing:

Included the dependency on pom.xml as :
```
        <dependency>
            <groupId>com.sksamuel.elastic4s</groupId>
            <artifactId>elastic4s-core_2.12</artifactId>
            <version>5.3.2</version>
        </dependency>

        <dependency>
            <groupId>com.sksamuel.elastic4s</groupId>
            <artifactId>elastic4s-tcp_2.12</artifactId>
            <version>5.3.2</version>
        </dependency>

        <dependency>
            <groupId>com.sksamuel.elastic4s</groupId>
            <artifactId>elastic4s-http_2.12</artifactId>
            <version>5.3.2</version>
        </dependency>

```
Next writing very simple code to create connection as : 
```
import com.sksamuel.elastic4s.ElasticDsl._
import com.sksamuel.elastic4s.{ElasticClient, ElasticsearchClientUri}

object HelloWorld {
  def main(args: Array[String]): Unit = {
    val client = ElasticClient.transport(ElasticsearchClientUri("localhost", 9300))
    client.execute { createIndex("places") }
  }
}
```

Now I get an error as : ElasticClient is deprecated ue tcpClient (I even tried with httpclient and not able to run the same). Any idea what I am doing wrong or this is an issue?
![screen shot 2017-05-04 at 12 28 15 pm](https://cloud.githubusercontent.com/assets/6836305/25693146/30ce095a-30c5-11e7-88d1-9b8f7b0eb9af.png)

**Comment by sksamuel** [comment] 2017-05-04 09:42
People have raised this before but I cannot duplicate it. What version of scala ?

**Comment by sksamuel** [comment] 2017-05-04 09:43
never mind I can see you're on 2.12.2

**Comment by prashanttct07** [comment] 2017-05-04 10:03
Yes, I am on 2.12 , Just checking if I should use ElasticClient or should rather use Http client , but unfortunately I am getting same error on httpclient as well.

**Comment by sksamuel** [comment] 2017-05-04 10:15
The error is actually in ElasticsearchClientUri, but I don't understand why it happens. If you look at the stack trace, scala is saying the unapply method doesn't exist on the regex class, which is all internal to Scala. It's a version mismatch somehow.

**Comment by prashanttct07** [comment] 2017-05-04 10:18
Any idea if I can add any dependency in pom to include the same. Like explicit including the scala 2.12 as
```
        <dependency>
            <groupId>org.scala-lang</groupId>
            <artifactId>scala-library</artifactId>
            <version>2.12.2</version>
        </dependency>

```

**Comment by solicode** [comment] 2017-05-04 10:34
I've never used Maven for Scala, but I've seen a similar thing happen to one of my coworkers. Trying to use 2.12 libraries with Scala 2.11 was the cause (since they're not binary compatible).

I wonder if this is the same issue? How do you specify the Scala version when using Maven? If it's not already set to 2.12, try setting it to that. Or if it's 2.11, using the `_2.11` variants should work, right?

**Comment by prashanttct07** [comment] 2017-05-05 05:03
I am using intellij and there on the global settings I am defining the scala 2.12 SDK. 

I tried the same on another windows machine and there I got different error as Error:scalac: Error: 
[xsbt/WeakLog java.lang.NoClassDefFoundError: xsbt/WeakLog](http://stackoverflow.com/questions/43785796/classnotfoundexception-xsbt-weaklog-scala-intellij)

**Comment by sksamuel** [comment] 2017-05-07 20:09
The issue will be in your setup with a clash between 2.11 and 2.12 dependencies.

I've added three sample projects - each using the http client - for sbt, maven and gradle. You can use whichever one you need to get started, but each shows that there's no issue with the client. 


https://github.com/sksamuel/elastic4s/tree/master/samples

**Closed by sksamuel** 2017-05-07 20:09 UTC

**Comment by prashanttct07** [comment] 2017-05-08 10:04
Thanks, @sksamuel : I will check and see if that works on my system.
