### ISSUE TITLE
SortDefinition can not be created. Missing addSort Method

### ISSUE THREAD

**Issue by alex-voigt** [sksamuel/elastic4s#743] opened 2017-02-10 09:07 UTC
```
java.lang.NoSuchMethodException: org.elasticsearch.search.builder.SearchSourceBuilder.addSort(org.elasticsearch.search.sort.SortBuilder)
[info]   at java.lang.Class.getMethod(Class.java:1786)
[info]   at com.sksamuel.elastic4s.search.SearchImplicits$SearchDefinitionShow$$anonfun$show$19.apply(SearchImplicits.scala:75)
[info]   at com.sksamuel.elastic4s.search.SearchImplicits$SearchDefinitionShow$$anonfun$show$19.apply(SearchImplicits.scala:74)
[info]   at scala.collection.IndexedSeqOptimized$class.foreach(IndexedSeqOptimized.scala:33)
[info]   at scala.collection.mutable.WrappedArray.foreach(WrappedArray.scala:35)
[info]   at com.sksamuel.elastic4s.search.SearchImplicits$SearchDefinitionShow$.show(SearchImplicits.scala:74)
[info]   at com.searchperience.frontend.core.builder.HighlightDefinitionBuilderSpec$$anonfun$1.apply$mcV$sp(HighlightDefinitionBuilderSpec.scala:45)
[info]   at com.searchperience.frontend.core.builder.HighlightDefinitionBuilderSpec$$anonfun$1.apply(HighlightDefinitionBuilderSpec.scala:12)
[info]   at com.searchperience.frontend.core.builder.HighlightDefinitionBuilderSpec$$anonfun$1.apply(HighlightDefinitionBuilderSpec.scala:12)
[info]   at org.scalatest.Transformer$$anonfun$apply$1.apply$mcV$sp(Transformer.scala:22)
```

Seems like the addSort Method is not existing in the SortBuilder.java in Elasticsearch when called by elastic4s 5.2.5 SearchBuilderFn (line 53) and SearchImplicits (line 75).

**Comment by sksamuel** [comment] 2017-02-10 09:42
Seems like a version mismatch. Do you have earlier versions of e4s lurking on your classpath.

**Comment by Dbzman** [comment] 2017-02-10 10:10
We looked into the elastic4s source code and noticed that you have the following lines in `SearchBuilderFn`:
```
  if (search.sorts.nonEmpty)
      search.sorts.foreach { sort =>
        builder.getClass.getMethod("addSort", classOf[SortBuilder[_]]).invoke(builder, SortBuilderFn.apply(sort))
      }
```
There you use the `SearchRequestBuilder` for building the definitions and you call "addSort".

The `SearchImplicits` class looks like its mostly copied from the `SearchBuilderFn` class but its using a totally different builder (from Elasticsearch directly) called `SearchSourceBuilder` which does not contain "addSort" but "sort".
I think its a copy & paste issue. :)

**Comment by sksamuel** [comment] 2017-02-10 10:45
Oh for the http client ?

**Comment by Dbzman** [comment] 2017-02-10 10:46
It's in the elastic4s-tcp package.

**Comment by sksamuel** [comment] 2017-02-10 12:05
I'm still confused as I don't remember changing anything here and the tests still pass but hopefully it'll be clear when I take a look :)

**Comment by sksamuel** [comment] 2017-02-13 08:17
Should be fixed in 5.2.6

**Closed** 2017-02-13 08:17 UTC

**Comment by Dbzman** [comment] 2017-02-13 08:31
Thank you very much! We'll check that. :)

**Comment by alex-voigt** [comment] 2017-02-13 12:35
Sorry, but for `SearchImplicits` it is still not fixed. :-)

**Comment by sksamuel** [comment] 2017-02-13 12:51
The http client. Should be fixed for tcp.

**Comment by Dbzman** [comment] 2017-02-13 14:15
Oh, now I see our mistake. We used the `SearchImplicits` from http even though we use the TCP client. Sorry for the confusion.

**Comment by Dbzman** [comment] 2017-02-14 17:59
Sorry for bothering you again.^^ We used the right `SearchImplicits`. 🙈 
Maybe I should give you some context of what we were trying to achieve: We have tests in our application which check the JSON output of the built definitions. To get that output we need to call `toString` on the builders. This works fine for things like `QueryDefinitions` where we can just use `QueryBuilderFn` to build the definitions and get the string representation in JSON.
For the `SearchDefinition` the only way to get a JSON output would be to use `SearchBuilderFn` but this requires to pass a client which we would like to avoid in these tests because it slows them down (by spinning up an embedded ES instance...).
Accidentally we stumbled accross the `SearchImplicits` class which seems to return a builder without having to pass a client. Problem here is that the fix you applied for `SearchBuilderFn` is not present in the `SearchImplicits`: 
https://github.com/sksamuel/elastic4s/blob/4922241c349527085109a049a02583d48eae6053/elastic4s-tcp/src/main/scala/com/sksamuel/elastic4s/search/SearchImplicits.scala#L75
We tried to fix it by ourselves but had some issues regarding types so maybe you could assist us here. :)
Thanks for your time!

**Comment by sksamuel** [comment] 2017-02-15 08:57
Ok so there's two sets of builders here, the ones for the TCP client and the ones for the HTTP client. Prior to 5.2.0 there was only the TCP client and it was all mixed in with definitions. As of 5.2.x I have been splitting out the definitions from the implementations so that the same DSL can be used for both the the TCP and the HTTP clients.

The TCP implementations are the ones that use clients and the java builders because they are available to that client. The HTTP implementations are meant to be dependency free so they build the json themselves.

The HTTP client is currently experimental and nowhere near complete since its new. I wouldn't mix and match the two. 

If you want to test that the json output is what you expect, it's harder with the TCP client because even with the builders exposed, most of them don't give you the json anyway. If you are using HTTP then you're going to run into the limitation that there's loads of queries / requests that it's yet to be implemented for, and maybe you could contribute missing ones, which you'd then be able to reference in your tests.

BTW, the best way to get the JSON is to do

`val json = client.show { request }`

Or if you don't want to create a client

`val json = SomeShowTypeclass.show(request)`

**Comment by Dbzman** [comment] 2017-02-15 10:12
Thanks for your detailed answer. That helped a lot to understand. :)
We found the show class for the `SearchDefinition` and tried to use it like this:
`SearchDefinitionShow.show(someDefinition)`
The problem is that this class throws the above mentioned exception when specifying the sort.
That was what I was referring to here: https://github.com/sksamuel/elastic4s/blob/4922241c349527085109a049a02583d48eae6053/elastic4s-tcp/src/main/scala/com/sksamuel/elastic4s/search/SearchImplicits.scala#L75
(Note, that this is the TCP package)

**Comment by sksamuel** [comment] 2017-02-15 10:20
Ok so the best thing to do is that the Show typeclass for TCP should share its builder with the actual request builder, which is almost the same thing but with sort working.

https://github.com/sksamuel/elastic4s/blob/master/elastic4s-tcp/src/main/scala/com/sksamuel/elastic4s/searches/SearchBuilderFn.scala

**Comment by Dbzman** [comment] 2017-02-15 12:36
Exactly, that would be perfect if they share the same builder. 😃 👍

**Comment by sksamuel** [comment] 2017-02-15 12:49
I look forward to the PR :)

**Comment by Reeebuuk** [comment] 2017-03-06 11:44
I have the same issue in 5.2.9

java.lang.NoSuchMethodException: org.elasticsearch.search.builder.SearchSourceBuilder.addSort(org.elasticsearch.search.sort.SortBuilder)

using .sortBy 

elastic4s-tcp search.SearchImplicits class.

**Comment by Reeebuuk** [comment] 2017-03-07 13:39
Not the pretties code but you get the picture :)

    val result = client execute {

      val searchQuery = boolQuery().must(mustQuery)

      val sort: Seq[FieldSortDefinition] = List(sortBy.map { y =>
        FieldSortDefinition(
          field = y.key,
          order =
            if (y.asc) SortOrder.ASC
            else
              SortOrder.DESC
        )
      }).flatten

      val req: SearchDefinition = search(indexTypeWithLanguage)
        .limit(sanitizedPageSize(pageSize))
        .from(from(pageSize, page))
        .query(searchQuery)
        .searchType(SearchType.QUERY_THEN_FETCH)
        .sortBy(sort)

      logger.info(">>> Executing query \n" + req.show)
      req

    }

**Comment by Reeebuuk** [comment] 2017-03-08 12:19
It actually fails completely on `req.show`.
If I comment it out it will execute the query but the sorting won't be applied and test are breaking ofc. But I cannot see a generated query then.

**Comment by alenegro81** [comment] 2017-03-08 17:35
I wrote a fix for this and submit a pull request, if someone would like to test it clone my fork

**Comment by sksamuel** [comment] 2017-03-08 19:35
Merged.

**Comment by Reeebuuk** [comment] 2017-03-09 06:19
Great, when can we expect a release? :)

**Comment by sksamuel** [comment] 2017-03-09 06:21
Next day or so.
