### ISSUE TITLE
Weird behavior with docAsUpsert while indexing strings

### ISSUE THREAD

**Issue by sakshamsharma** [sksamuel/elastic4s#644] opened 2016-10-11 19:43 UTC
Here's the command I've been trying to use:

```
update id userId in indexName / typeName docAsUpsert UserInfo(userInfo)
```

I have these custom wrappers (seemingly of no use):

```
      case class UserInfo(data: String) extends DocumentSource {
        def json: String = data
      }

      implicit object UserInfoIndexable extends Indexable[UserInfo] {
        override def json(s: UserInfo): String = s.data
      }
```

The string I'm trying to index looks like this:

```
s"""{"key1": "value2"}"""
```

Now, as long as I'm actually updating a previous entry, it works fine enough. But the moment I try to insert an object whose ID doesn't exist, it throws a `DocumentMissingException`. This has left me baffled, any light shed would be nice.

Of note is that it works fine if I'm indexing a `source` instead of `doc`, but again, I cannot use `source` to index non-existant IDs as well.

Another note: Copying the example off the guide/update.md page, the provided map works fine as well, and I suspect a DocumentMap would work fine too. What am I doing wrong with DocumentSource then? Is that string I'm using somehow flawed?

**Comment by sksamuel** [comment] 2016-10-11 21:01
Possibly badly named methods, but docAsUpsert means use this doc for updates. It won't use it for inserts.

You're best off doing this.

`update(id).in(index/type).docAsUpsert(true).source(obj)`

And you'll need the indexable in scope.

**Comment by sakshamsharma** [comment] 2016-10-12 16:37
I see that your suggestion works. Thanks a lot!
But I'm still confused, why would a simple map (associative list) work with docAsUpsert, but a document would not?

**Comment by sakshamsharma** [comment] 2016-10-24 06:00
Pre-closing bump

**Comment by sksamuel** [comment] 2016-10-24 06:06
I think its a duplicate of https://github.com/sksamuel/elastic4s/issues/592

**Closed** 2016-11-05 11:39 UTC
Labels: bug
