### ISSUE TITLE
在7.0版本中,自定义Tokenizer异常,  for example：NGramTokenizer 

### ISSUE THREAD

**Issue by 296431555** [sksamuel/elastic4s#1798] opened 2019-07-16 08:23 UTC
自定义分析器，最终生成的JSON如下：
`
{
	"settings": {
		"index": {
			"number_of_shards": 10,
			"number_of_replicas": 1
		},
		"analysis": {
			"analyzer": {
				"ngram_analyzer": {
					"type": "custom",
					"tokenizer": "ngram_tokenizer"
				}
			},
			"tokenizer": {
				"ngram_tokenizer": {
					"ngram_tokenizer": {
						"type": "nGram",
						"min_gram": 1,
						"max_gram": 20,
						"token_chars": ["letter", "digit"]
					}
				}
			}
		}
	},
	"mappings": {
		"properties": {
			"baz": {
				"type": "text",
				"analyzer": "ik_max_word",
				"search_analyzer": "ik_smart",
				"store": true
			},
			"number": {
				"type": "text",
				"analyzer": "ngram_analyzer",
				"store": true
			}
		}
	},
	"aliases": {
		"goo2": {}
	}
}
`

Fix Bug：
case class NGramTokenizer(override val name: String,
                          minGram: Int = 1,
                          maxGram: Int = 2,
                          tokenChars: Iterable[String] = Nil) extends Tokenizer {

  override def build: XContentBuilder = {
    val b = XContentFactory.jsonBuilder().startObject(name)  // 这里去除【.startObject(name)】
    b.field("type", "nGram")
    b.field("min_gram", minGram)
    b.field("max_gram", maxGram)
    if (tokenChars.nonEmpty)
      b.array("token_chars", tokenChars.toArray)
    b.endObject()
  }

  def minMaxGrams(min: Int, max: Int): NGramTokenizer = copy(minGram = min, maxGram = max)
  def tokenChars(tokenChars: Iterable[String]): NGramTokenizer = copy(tokenChars = tokenChars)
  def tokenChars(tokenChar: String, rest: String*): NGramTokenizer = copy(tokenChars = tokenChar +: rest)
}

**Comment by peri4n** [comment] 2019-07-16 14:24
This is a duplicate of #1795

**Comment by sksamuel** [comment] 2019-08-11 17:14
Please try latest release with this fixed.

**Closed by sksamuel** 2019-08-11 17:14 UTC
