### ISSUE TITLE
elastic4s-core 7.12.1 references unpublished artifact elastic4s-client-core

### ISSUE THREAD

**Issue by mprihoda** [sksamuel/elastic4s#2402] opened 2021-04-26 10:58 UTC
Hi,

the 7.12.1 version references elastic4s-client-core in POM file, but there is no such artifact published in the Maven repo. It seems it has been introduced recently in build.sbt and has no associated sources.

Version 7.4.2 seems to be referencing the client-core as well, older versions do not.

**Comment by giftig** [comment] 2021-04-29 16:21
I just ran into this as well, resolved it by rolling back to 7.12.0 instead.

**Comment by sksamuel** [comment] 2021-04-29 16:24
I'll do another release tonight.

**Comment by brunoballekens** [comment] 2021-05-07 07:04
Have the same problems with the 7.11.2

**Comment by sksamuel** [comment] 2021-05-07 17:14
There's currently publication issues with maven - I've raised a ticket to
sonatype to move my projects to their new faster host.
Hopefully back up today at some point and I can republish these broken
libs.

**Comment by dayyan** [comment] 2021-05-12 23:44
> Have the same problems with the 7.11.2

7.10.6 as well.

**Comment by ptrdom** [comment] 2021-05-17 12:41
7.10.5 is also affected.

**Comment by ramazanyich** [comment] 2021-05-20 10:15
Is there any progress for solving the problem? We need to depend on new version of elastic4s, but cannot do it due to missing elastic4s-client-core jar

**Comment by pwheimann** [comment] 2021-05-20 13:59
I'm also running into this issue, with 7.10.5 and 7.10.6...and seems I cannot upgrade to match my upgraded version of ES.

**Comment by sksamuel** [comment] 2021-05-20 14:19
I'll figure this out and release again shortly

**Comment by sksamuel** [comment] 2021-05-22 02:04
So 7.12.1 looks good. I've also released 7.10.7 and 7.11.4

**Comment by stefansperber** [comment] 2021-05-22 23:14
I tried the dependency upgrade this morning but `elastic4s-client-core` still seems to be missing from the central repository https://search.maven.org/search?q=elastic4s-client-core

**Comment by sksamuel** [comment] 2021-05-22 23:19
Client core is 7.12 only. What version are you using?

**Comment by stefansperber** [comment] 2021-05-23 00:32
We're using 7.12.0 at the moment.

**Comment by sksamuel** [comment] 2021-05-23 01:44
did you try 7.12.1 ?

**Comment by stefansperber** [comment] 2021-05-23 05:20
Yes, I did. We want to upgrade from 7.12.0 to 7.12.1. The dependency upgrade PR does not build as it cannot find elastic4s-client-core (it doesn't seem to exist? https://search.maven.org/search?q=elastic4s-client-core)

**Comment by ithinkicancode** [comment] 2021-05-23 12:38
> Yes, I did try. We want to upgrade from 7.12.0 to 7.12.1. The dependency upgrade PR does not build as it cannot find elastic4s-client-core (it doesn't seem to exist? https://search.maven.org/search?q=elastic4s-client-core)

I can confirm this. I'm still getting the "Error downloading com.sksamuel.elastic4s:elastic4s-client-core_2.13:7.12.1" error.

If you go to https://repo1.maven.org/maven2/com/sksamuel/elastic4s/, you will notice there is no subdirectories with the prefix of `elastic4s-client-core_`. Seems the problem still persists, unfortunately.

**Comment by sksamuel** [comment] 2021-05-23 16:42
Ok 7.12.2 looks good. elastic4s-client-core can be seen.

https://repo.maven.apache.org/maven2/com/sksamuel/elastic4s/elastic4s-client-core_2.13/

**Comment by stefansperber** [comment] 2021-05-24 07:11
Thanks, Sam!

In the end, we decided to postpone the upgrade as we can't do the cats-effect 3.x update yet.

**Comment by ramazanyich** [comment] 2021-05-24 08:47
7.11.4 worked well! It does not depend on elastic4s-client-core now i suppose...

**Comment by ptrdom** [comment] 2021-05-31 11:20
@sksamuel Could you release a 7.10.x version with client-core artifact present in repository? Currently 7.10.5 and above do not work because of the missing artifact, and those are quite important - 7.10 is the latest Elasticsearch version supported by AWS and 7.10.5 and above have an important fix for URL encoding.

**Comment by sksamuel** [comment] 2021-05-31 11:38
7.10.7 shouldn't need client core as that's 7.12 only. 7.10.5/6 was
released as a mistake. Can you try 7.10.7 and see if that's good for you.

**Comment by ptrdom** [comment] 2021-05-31 13:46
7.10.7 seems good, thanks!

**Comment by dayyan** [comment] 2021-06-10 16:46
- [x] 7.12
- [x] 7.11
- [x] 7.10

Do we need any more? If not lets close!

**Closed** 2021-06-10 17:53 UTC
