### ISSUE TITLE
HttpClient does not URL encode document IDs

### ISSUE THREAD

**Issue by kbedel** [sksamuel/elastic4s#1039] opened 2017-08-23 17:52 UTC
The HttpClient does not URL encode document IDs. This causes issues when trying to do things like index/get/delete documents where the ID has characters such as a space in it. This IDs work fine in the TcpClient.

For example, this test passes:
```
"tcp client" should {
  "index a document" when {
    "id has a space" in {
      client.execute {
        indexInto("test" / "indextest").doc("{}").id("test id")
      }.await
    }
  }
}
```

while this one:
```
"http client" should {
  "index a document" when {
    "id has a space" in {
      httpClient.execute {
        indexInto("test" / "indextest").doc("{}").id("test id")
      }.await
    }
  }
}
```

results in the following error:
```
Illegal character in path at index 20: /test/indextest/test id
java.lang.IllegalArgumentException: Illegal character in path at index 20: /test/indextest/test id
	at org.elasticsearch.client.RestClient.buildUri(RestClient.java:576)
	at org.elasticsearch.client.RestClient.performRequestAsync(RestClient.java:320)
	at org.elasticsearch.client.RestClient.performRequestAsync(RestClient.java:268)
	at com.sksamuel.elastic4s.http.HttpExecutable$RichRestClient.$anonfun$async$5(HttpExecutable.scala:49)
	at com.sksamuel.elastic4s.http.HttpExecutable$RichRestClient.$anonfun$async$5$adapted(HttpExecutable.scala:49)
	at com.sksamuel.elastic4s.http.HttpExecutable$RichRestClient$$Lambda$1552/1889365477.apply(Unknown Source)
	at com.sksamuel.elastic4s.http.HttpExecutable$RichRestClient.future(HttpExecutable.scala:26)
	at com.sksamuel.elastic4s.http.HttpExecutable$RichRestClient.async(HttpExecutable.scala:50)
	at com.sksamuel.elastic4s.http.index.IndexImplicits$IndexHttpExecutable$.execute(IndexImplicits.scala:39)
	at com.sksamuel.elastic4s.http.index.IndexImplicits$IndexHttpExecutable$.execute(IndexImplicits.scala:12)
	at com.sksamuel.elastic4s.http.HttpClient.execute(HttpClient.scala:23)
	at com.sksamuel.elastic4s.http.HttpClient.execute$(HttpClient.scala:23)
	at com.sksamuel.elastic4s.http.HttpClient$$anon$1.execute(HttpClient.scala:37)
```

Manually using URLEncoder.encode works, but it seems like this should be part of the client since it works in the TcpClient.

**Comment by sksamuel** [comment] 2017-08-23 20:44
The two test cases look the same.

**Comment by kbedel** [comment] 2017-08-23 20:46
The difference is just in what client is used. The one with HttpClient client fails, while the one with TcpClient passes. Sorry, this wasn't very clear in the tests.

**Comment by sksamuel** [comment] 2017-08-23 20:48
Yes sorry, it is clear I was just blind.

**Comment by sksamuel** [comment] 2017-10-03 13:08
Fixed in 6.0.0-rc1.

**Closed by sksamuel** 2017-10-03 13:08 UTC
Labels: bug

**Comment by WayneWang12** [comment] 2017-10-17 10:10
Hi @sksamuel ! Did you test `get` operation? It seems that when using `get` like 
```
val r = client.execute(
      get(uuid).from(EntityServiceSubscriber.indexNameByTenantId(tenantId) / entityType)
)
r.await
```
the result future just get time out and returns no response. I've encounter this in version `6.0.0-rc1`

**Comment by sksamuel** [comment] 2017-10-17 10:40
These tests test `get` operation by id.
https://github.com/sksamuel/elastic4s/blob/master/elastic4s-tests/src/test/scala/com/sksamuel/elastic4s/get/GetTest.scala#L43-L74

**Comment by WayneWang12** [comment] 2017-10-17 10:48
OK. I've change it from `r.map(_.right.get).await` to `r.await.right.get`. Seems the latter one is OK but the former one just gets timeout. It doesn't make any sense. I'll try on the source code if this will happen.

**Comment by sksamuel** [comment] 2017-10-17 10:56
Should work either way shouldn't it.

**Comment by WayneWang12** [comment] 2017-10-17 11:06
Yes, it should. But actually there is a difference. That's why it spends me a lot of time. 
this one timeouts:
![image](https://user-images.githubusercontent.com/6812513/31661587-db009b74-b36d-11e7-9c8d-cd097159cc40.png)

this one works fine:
![image](https://user-images.githubusercontent.com/6812513/31661665-1975bb96-b36e-11e7-95c5-7ce4555da2bb.png)

Most wierd thing I've meet in these days...........

**Comment by WayneWang12** [comment] 2017-10-17 11:08
Firstly I think it is due to url encoding because I've get across the problem of encoding, and come to this issue. I thought it's because of the encoding. Seems it is not. If nessacery I can open a new issue for this.

**Comment by sksamuel** [comment] 2017-10-17 11:09
It's more likely to be something else than the library if right.get works wouldn't you think, but you can open another issue if you prefer.

**Comment by WayneWang12** [comment] 2017-10-17 11:11
I'll try on the library testing. If it is reproduced, then I'll open a new issue for it.

**Comment by francisdb** [comment] 2017-11-03 16:28
Will this fix be backported to 5.x?

**Comment by sksamuel** [comment] 2017-11-03 16:29
If you make a PR for it :)

**Comment by francisdb** [comment] 2017-11-04 16:22
@sksamuel not it's your turn to get me a release :-)
